[workspace]
authors = ["Stephen Cross <stephencross86@gmail.com>"]
channels = ["conda-forge"]
name = "mia-python"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.12"

[pypi-dependencies]
jpype1 = "==1.5.1"
jupyter = ">=1.1.1"
matplotlib = ">=3.10.0"
pyimagej = ">=1.6.0"
prettytable = ">=3.17.0, <4"
