[workspace]
authors = ["Stephen Cross <stephencross86@gmail.com>"]
channels = ["conda-forge"]
name = "mia-python"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.7,<3.14"

[pypi-dependencies]
jpype1 = ">=1.6.0"
jupyter = ">=1.1.1"
matplotlib = ">=3.10.0"
pyimagej = ">=1.6.0"
